services:
  ytdlp-job:
    build:
      context: .
      dockerfile: Dockerfile

    network_mode: "container:gluetun_ytdlp"

    volumes:
      - /mnt/Universe/Media/Ourida:/app/downloads

    environment:
      - PUID=568
      - PGID=568
      - TZ=America/Detroit

    # (Optional) If you pass args to your entrypoint, you can define a default command
    # command: ["https://thewebsite.xyz/video/123"]