# File name format
-o "%(series)s/%(title)s.%(ext)s"

# Parallelization
-N 8

# VPN
--proxy "socks5://10.10.10.10:1080"

--lazy-playlist

--break-on-existing

--break-per-input

# Never invoke ffmpeg to fix videos
--fixup never

# Download location
-P /app/downloads

# Archive of existing downloads
--download-archive /app/downloads/downloaded.txt

# List of urls to download
-a /app/downloads/series_urls.txt

--no-config
