# File name format
-o "%(series)s/%(title)s.%(ext)s"

# Parallelization
-N 8

# Suppress the warning about running a 90 day old version of ytdlp
--no-update

# Download location
-P /app/downloads

# Archive of existing downloads
--download-archive /app/downloads/downloaded.txt

--no-config
