# File name format
-o "%(series)s/%(title)s.%(ext)s"

# Parallelization
-N 8

# VPN
# --proxy "socks5://10.10.10.10:40000"

--lazy-playlist

# --break-on-existing

# --break-per-input

# As soon as one video fails (usually due to geo-restriction), abort the entire run
#--abort-on-error

# If few videos fail, maybe there's something fundamentally broken.
--skip-playlist-after-errors 3

# Never invoke ffmpeg to fix videos
# --fixup never

# Don't spam progress
--progress-delta 10

# Suppress the warning about running a 90 day old version of ytdlp
--no-update

# Download location
-P /app/downloads

# Archive of existing downloads
--download-archive /app/downloads/downloaded.txt

# List of urls to download
-a /app/downloads/series_urls.txt

--no-config
