# File name format
-o "%(series)s/%(series)s %(episode)s.%(ext)s"

# Parallelization
-N 8

# VPN
# Aradrama sometimes returns 403 Forbidden when going thru a VPN
#--proxy "socks5://10.10.10.10:1080"

# Never invoke ffmpeg to fix videos
--fixup never

# Download location
-P /app/downloads

--no-check-certificates

# Archive of existing downloads
# Download archive isn't useful since these downloads don't have the right (ie_key, id) pair.
# --download-archive /app/downloads/downloaded.txt

--no-config
